#!/bin/sh
# appinstaller
# (C) 2007 Fabian Wuertz <xadras@sidux.com>
# (C) 2007 Stefan Lippers-Hollmann <s.l-h@gmx.de>
# License: GPL

[ -z "${1}" ] && exit 0

[ "$(id -u)" -ne 0 ] && DISPLAY="" exec su-me "$0" "$@"

apt-get update
apt-get install $1

echo ""
echo "<Enter> druecken um fortzufahren..."
read DUMMY

