#!/bin/sh
# appinstaller
# (C) 2007 Fabian Wuertz <xadras@sidux.com>
# (C) 2007-2008 Stefan Lippers-Hollmann <s.l-h@gmx.de>
# License: GPL

[ -z "${1}" ] && exit 0

if [ "$(id -u)" -ne 0 ]; then
	[ -x "$(which su-to-root)" ] && exec su-to-root -c "${0} $@"
	printf "ERROR: $0 needs root capabilities, please start it as root.\n\n" >&2
	exit 1
fi

apt-get update
apt-get install $@

echo ""
echo "<Enter> druecken um fortzufahren..."
read DUMMY

